name: deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy-test:
    name: "Deploy to test-srs.skauting.cz"
    runs-on: ubuntu-18.04
    container:
      image: fmasa/lebeda:7.3
    env:
      CONFIG_DATABASE_HOST: localhost
      CONFIG_DATABASE_NAME: db009903
      CONFIG_DATABASE_PASSWORD: ${{ secrets.CONFIG_DATABASE_PASSWORD }}
      CONFIG_DATABASE_USER: us009903
      CONFIG_MAIL_HOST:
      CONFIG_MAIL_PASSWORD:
      CONFIG_MAIL_PORT: 0
      CONFIG_MAIL_SECURE:
      CONFIG_MAIL_SMTP: false
      CONFIG_MAIL_USERNAME:
      CONFIG_SKAUTIS_APPLICATION_ID: cb35144d-2ab7-4106-80fb-6527594f9873
      CONFIG_SKAUTIS_TEST_MODE: true
      DEPLOY_SSH_HOST: test-srs.skauting.cz
      DEPLOY_SSH_IP: 81.31.46.138
      DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      DEPLOY_SSH_PORT: 28
      DEPLOY_SSH_USERNAME: vu009903
    steps:
      - uses: actions/checkout@v2
      # Copy & paste from https://github.com/actions/cache/blob/master/examples.md#php---composer
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Setup SSH key
        run: |
#          mkdir -p ~/.ssh
          ssh-keyscan -H "${DEPLOY_SSH_HOST}","${DEPLOY_SSH_IP}" >> /root/.ssh/known_hosts
          eval `ssh-agent -s`
          echo "${DEPLOY_SSH_KEY}" | tr -d '\r' | ssh-add -
#          cat ~/.ssh/known_hosts
          ssh -v "${DEPLOY_SSH_USERNAME}@${DEPLOY_SSH_HOST}" -p ${DEPLOY_SSH_PORT} mkdir test
      - run: phing deploy

