name: deploy-srs

on:
  push:
    branches:
    - master

jobs:
  build:
    name: "Build SRS"
    runs-on: ubuntu-latest
    container:
      image: fmasa/lebeda:7.3
    steps:
      - uses: actions/checkout@v2
          
      # Copy & paste from https://github.com/actions/cache/blob/master/examples.md#php---composer
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      
      - run: composer install --no-dev
      
      - run: |
          mkdir build
          cp -r app build
          cp -r backup build
          cp -r log build
          cp -r migrations build
          cp -r temp build
          cp -r vendor build
          cp -r www build
          cp .htaccess build
          mv build/app/config/production.local.neon build/app/config/local.neon
          rm build/app/config/*.local.neon

      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '__'
          tokenSuffix: '__'
          files: 'build/app/config/local.neon'
        env:
          CONFIG_DATABASE_HOST: "localhost"
          CONFIG_DATABASE_NAME: "srs"
          CONFIG_DATABASE_USER: "srs"
          CONFIG_DATABASE_PASSWORD: ${{ secrets.SRS_DB_PASSWORD }}
          CONFIG_SKAUTIS_APPLICATION_ID: ${{ secrets.SRS_APP_ID }}
          CONFIG_SKAUTIS_TEST_MODE: true

      - run: |
          tar -zcvf release.tar.gz build

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: "srs.skauting.cz"
          username: "vu008925"
          key: ${{ secrets.SRS_SSH_KEY }}
          port: 28
          source: "release.tar.gz"
          target: ""
 
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: "srs.skauting.cz"
          username: "vu008925"
          key: ${{ secrets.SRS_SSH_KEY }}
          port: 28
          script_stop: true
          script: |
            tar -xvzf release.tar.gz -C releases/test
            rm release.tar.gz
            rm www && ln -s releases/test/www www
